# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'


steps:

# SonarCloud Stuff for API
- task: SonarCloudPrepare@1
  displayName: 'SonarCloud Prepare'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'repeat-committers'
    scannerMode: 'MSBuild'
    projectKey: 'Repeat-Committers_Whats-That-Song'
    projectName: 'Whats That Song'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll, **/WhatsThatSong/wwwroot/**
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/*.xml


# Find the API Solution File
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: './WhatsThatSong/WhatsThatSong.sln'
    feedsToUse: 'select'

- script: dotnet build ./WhatsThatSong/WhatsThatSong.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '.Net Test'
  inputs:
    command: 'test'
    projects: './WhatsThatTest'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/MyCoverage/'
    publishTestResults: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Cobertura Code Coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/MyCoverage/coverage.cobertura.xml'

- task: SonarCloudAnalyze@1
  displayName: 'Analyze on SonarCloud'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: '.Net Publish'
  inputs:
    command: 'publish'
    #publishWebProjects: true
    publishWebProjects: false
    # Added Code
    projects: '/WhatsThatSong/WhatsThatSong.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    # Added Code
    zipAfterPublish: true

# Added Task
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
# Added Task

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy ASP.NET API'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(177e072a-ef5e-4a5f-94f4-d006ea8b8575)'
    appType: 'webApp'
    WebAppName: 'WhatsThatSong'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: AzureAppServiceManage@0
  displayName: 'Start App Service'
  inputs:
    azureSubscription: 'Azure subscription 1(177e072a-ef5e-4a5f-94f4-d006ea8b8575)'
    Action: 'Start Azure App Service'
    WebAppName: 'WhatsThatSong'